// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfoilpoobatiebymmppb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlmb2lscG9vYmF0aWVieW1tcHBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMDY2NjMsImV4cCI6MjA2NDc4MjY2M30.azgg6BSJ8GBmwlfSFIVK8Orywxtg-xorjo1rrTYYc1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);